### ISSUE TITLE
引入hippo4j-spring-boot-starter配置项，bean初始化失败

### ISSUE THREAD

**Issue by HaloAlessia** [acmenlt/dynamic-threadpool#80]
客户端配置
> spring.application.name=data-inspector
spring.dynamic.thread-pool.server-addr= http://127.0.0.1:6691
spring.dynamic.thread-pool.namespace= tfc
spring.dynamic.thread-pool.item-id= data-inspector
spring.dynamic.thread-pool.username= admin
spring.dynamic.thread-pool.password= 123456
spring.dynamic.thread-pool.enable= true

启动类配置
> @SpringBootApplication(exclude={DataSourceAutoConfiguration.class, HibernateJpaAutoConfiguration.class},
        scanBasePackages = {"com.xx.asap.data.inspector.rule", "com.xx.asap.data.inspector.web.context","com.xx.asap.data.inspector.web.controller", "com.xx.dtboost.fr.sdk.client"})
@EnableAsync
@EnableScheduling
@EnableCaching
@EnableDynamicThreadPool

配置类

> @Slf4j
@Data
@Configuration
public class ThreadPoolConfig {

    @Bean
    @DynamicThreadPool
    public ThreadPoolExecutor realTimeThreadPoolExecutor() {
        return ThreadPoolBuilder.builder()
                .threadFactory(REAL_TIME)
                .dynamicPool()
                .waitForTasksToCompleteOnShutdown(true)
                .awaitTerminationMillis(5000)
                .build();
    }

报错
> 16:52:21.408 [main] ERROR o.s.boot.SpringApplication [] - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.aliyun.cosmo.boot.core.CsmMessageSourceAutoConfiguration': Initialization of bean failed; nested exception is java.lang.AbstractMethodError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.initMessageSource(AbstractApplicationContext.java:713)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:530)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:123)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:666)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:353)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1082)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1071)
	at com.aliyun.asap.data.inspector.web.InspectorApplication.main(InspectorApplication.java:66)
Caused by: java.lang.AbstractMethodError: null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1622)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	... 23 common frames omitted
16:52:21.409 [main] INFO  c.a.a.d.i.web.InspectorApplication [] - [Ljava.lang.StackTraceElement;@5584d9c6java.lang.AbstractMethodErrorError creating bean with name 'com.aliyun.cosmo.boot.core.CsmMessageSourceAutoConfiguration': Initialization of bean failed; nested exception is java.lang.AbstractMethodError
Process finished with exit code 0

疑似引入客户端后 @AutoConfigureBefore失效了？另外我自己的项目依赖引入的spring-boot是1.5.22.RELEASE

**Comment by acmenlt** [comment]
您好，核心类 `DynamicThreadPoolPostProcessor` 依赖 Spring 后置处理器，但是 1.5.x 的 SpringBoot 版本 `BeanPostProcessor` 不存在 default 方法，导致启动会有问题

所以，我需要将 `DynamicThreadPoolPostProcessor` 实现下缺失的 `postProcessBeforeInitialization` 方法。请等待明天发布的 1.0.0-beta.6 版本

最后，上述报错是否是由此问题引起的，还有待研究。

**Comment by HaloAlessia** [comment]
debug 信息看起来是这个问题引起的，那就等你发布新版咯
> Error creating bean with name 'messageSource' defined in class path resource [com/aliyun/cosmo/boot/core/CsmMessageSourceAutoConfiguration.class]: factory-bean 'com.aliyun.cosmo.boot.core.CsmMessageSourceAutoConfiguration' (or a BeanPostProcessor involved) returned null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:374)

**Comment by acmenlt** [comment]
已升级 1.0.0-beta.6 版本，请在验证无问题后关闭 Issue，谢谢。

**Comment by HaloAlessia** [comment]
works for me now,thx

**Comment by netyjq** [comment]
你好，我和[HaloAlessia](https://github.com/HaloAlessia) 的问题类似，我也是使用 springboot 1.5.19.RELEASE 最新版本，接入 hippo4j-spring-boot-starter 提示下面的错误，疑似这个问题又复发了？
 ```
<dependency>
    <groupId>cn.hippo4j</groupId>
    <artifactId>hippo4j-spring-boot-starter</artifactId>
    <version>1.5.0</version>
</dependency>

``` 
       

Caused by: java.lang.AbstractMethodError: null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:407)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1623)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	... 25 common frames omitted

**Comment by netyjq** [comment]
[demo.zip](https://github.com/opengoofy/hippo4j/files/12394592/demo.zip)

代码示例

**Comment by magestacks** [comment]
> [demo.zip](https://github.com/opengoofy/hippo4j/files/12394592/demo.zip)
> 
> 代码示例

目前赞不支持 1.5.x 版本 SpringBoot，Web 容器那块有点有点冗余，后续会重构。
